#############################################################################
# Makefile for building: NEW_OFC_GUI
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Jun 23 15:11:14 2013
# Project:  NEW_OFC_GUI.pro
# Template: app
# Command: /home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec ../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile NEW_OFC_GUI.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_SCRIPT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -I. -I../../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I../../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtNetwork -I../../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtGui -I../../../QtSDK/Desktop/Qt/4.8.1/gcc/include/QtScript -I../../../QtSDK/Desktop/Qt/4.8.1/gcc/include -I. -Iheaders -I../../zeromq2-1/include -I../OGDF -I../../jansson-2.3.1/src -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/lib -lzmq -L/home/liudanny/SourceCode/qt4_projects/OGDF/_release -lOGDF -ljansson -lQtScript -L/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/lib -lQtGui -L/usr/X11R6/lib64 -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/annotation.cpp \
		src/edge.cpp \
		src/graphwidget.cpp \
		src/main.cpp \
		src/node.cpp \
		src/mainwindow.cpp \
		src/httpget.cpp moc_graphwidget.cpp \
		moc_nzmqt.cpp \
		moc_PubSubClient.cpp \
		moc_PubSubServer.cpp \
		moc_ReqRepClient.cpp \
		moc_ReqRepServer.cpp \
		moc_mainwindow.cpp \
		moc_httpget.cpp \
		qrc_NEW_OFC_GUI.cpp
OBJECTS       = annotation.o \
		edge.o \
		graphwidget.o \
		main.o \
		node.o \
		mainwindow.o \
		httpget.o \
		moc_graphwidget.o \
		moc_nzmqt.o \
		moc_PubSubClient.o \
		moc_PubSubServer.o \
		moc_ReqRepClient.o \
		moc_ReqRepServer.o \
		moc_mainwindow.o \
		moc_httpget.o \
		qrc_NEW_OFC_GUI.o
DIST          = ../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		NEW_OFC_GUI.pro
QMAKE_TARGET  = NEW_OFC_GUI
DESTDIR       = 
TARGET        = NEW_OFC_GUI

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: NEW_OFC_GUI.pro  ../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++/qmake.conf ../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtScript.prl \
		/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl \
		/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl \
		/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtNetwork.prl
	$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile NEW_OFC_GUI.pro
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/linux.conf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-unix.conf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-unix.conf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/release.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtScript.prl:
/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtCore.prl:
/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtGui.prl:
/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/linux-g++ -o Makefile NEW_OFC_GUI.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/NEW_OFC_GUI1.0.0 || $(MKDIR) .tmp/NEW_OFC_GUI1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/NEW_OFC_GUI1.0.0/ && $(COPY_FILE) --parents headers/annotation.h headers/edge.h headers/graphwidget.h headers/node.h headers/nzmqt/nzmqt.hpp headers/nzmqt/common/Tools.h headers/nzmqt/pubsub/PubSubClient.h headers/nzmqt/pubsub/PubSubServer.h headers/nzmqt/reqrep/ReqRepClient.h headers/nzmqt/reqrep/ReqRepServer.h headers/mainwindow.h headers/httpget.h .tmp/NEW_OFC_GUI1.0.0/ && $(COPY_FILE) --parents NEW_OFC_GUI.qrc .tmp/NEW_OFC_GUI1.0.0/ && $(COPY_FILE) --parents src/annotation.cpp src/edge.cpp src/graphwidget.cpp src/main.cpp src/node.cpp src/mainwindow.cpp src/httpget.cpp .tmp/NEW_OFC_GUI1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/NEW_OFC_GUI1.0.0/ && (cd `dirname .tmp/NEW_OFC_GUI1.0.0` && $(TAR) NEW_OFC_GUI1.0.0.tar NEW_OFC_GUI1.0.0 && $(COMPRESS) NEW_OFC_GUI1.0.0.tar) && $(MOVE) `dirname .tmp/NEW_OFC_GUI1.0.0`/NEW_OFC_GUI1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/NEW_OFC_GUI1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_graphwidget.cpp moc_nzmqt.cpp moc_PubSubClient.cpp moc_PubSubServer.cpp moc_ReqRepClient.cpp moc_ReqRepServer.cpp moc_mainwindow.cpp moc_httpget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_graphwidget.cpp moc_nzmqt.cpp moc_PubSubClient.cpp moc_PubSubServer.cpp moc_ReqRepClient.cpp moc_ReqRepServer.cpp moc_mainwindow.cpp moc_httpget.cpp
moc_graphwidget.cpp: headers/edge.h \
		headers/node.h \
		headers/annotation.h \
		headers/graphwidget.h
	/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) headers/graphwidget.h -o moc_graphwidget.cpp

moc_nzmqt.cpp: headers/nzmqt/nzmqt.hpp
	/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) headers/nzmqt/nzmqt.hpp -o moc_nzmqt.cpp

moc_PubSubClient.cpp: headers/nzmqt/pubsub/PubSubClient.h
	/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) headers/nzmqt/pubsub/PubSubClient.h -o moc_PubSubClient.cpp

moc_PubSubServer.cpp: headers/nzmqt/pubsub/PubSubServer.h
	/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) headers/nzmqt/pubsub/PubSubServer.h -o moc_PubSubServer.cpp

moc_ReqRepClient.cpp: headers/nzmqt/reqrep/ReqRepClient.h
	/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) headers/nzmqt/reqrep/ReqRepClient.h -o moc_ReqRepClient.cpp

moc_ReqRepServer.cpp: headers/nzmqt/reqrep/ReqRepServer.h
	/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) headers/nzmqt/reqrep/ReqRepServer.h -o moc_ReqRepServer.cpp

moc_mainwindow.cpp: headers/httpget.h \
		headers/graphwidget.h \
		headers/edge.h \
		headers/node.h \
		headers/annotation.h \
		headers/mainwindow.h
	/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) headers/mainwindow.h -o moc_mainwindow.cpp

moc_httpget.cpp: headers/httpget.h
	/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc $(DEFINES) $(INCPATH) headers/httpget.h -o moc_httpget.cpp

compiler_rcc_make_all: qrc_NEW_OFC_GUI.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_NEW_OFC_GUI.cpp
qrc_NEW_OFC_GUI.cpp: NEW_OFC_GUI.qrc \
		images/print.png \
		images/new.png \
		images/save.png \
		images/undo.png \
		images/topology.png \
		images/REST.png
	/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/bin/rcc -name NEW_OFC_GUI NEW_OFC_GUI.qrc -o qrc_NEW_OFC_GUI.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/home/liudanny/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

annotation.o: src/annotation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o annotation.o src/annotation.cpp

edge.o: src/edge.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o edge.o src/edge.cpp

graphwidget.o: src/graphwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphwidget.o src/graphwidget.cpp

main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

node.o: src/node.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o src/node.cpp

mainwindow.o: src/mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

httpget.o: src/httpget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o httpget.o src/httpget.cpp

moc_graphwidget.o: moc_graphwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphwidget.o moc_graphwidget.cpp

moc_nzmqt.o: moc_nzmqt.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nzmqt.o moc_nzmqt.cpp

moc_PubSubClient.o: moc_PubSubClient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PubSubClient.o moc_PubSubClient.cpp

moc_PubSubServer.o: moc_PubSubServer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PubSubServer.o moc_PubSubServer.cpp

moc_ReqRepClient.o: moc_ReqRepClient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ReqRepClient.o moc_ReqRepClient.cpp

moc_ReqRepServer.o: moc_ReqRepServer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ReqRepServer.o moc_ReqRepServer.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_httpget.o: moc_httpget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_httpget.o moc_httpget.cpp

qrc_NEW_OFC_GUI.o: qrc_NEW_OFC_GUI.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_NEW_OFC_GUI.o qrc_NEW_OFC_GUI.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

